title = "vectronic"
baseURL = "https://vectronic.io/"
languageCode = "en-gb"
enableRobotsTXT = true
theme = "vectronic"
sectionPagesMenu = "global"
paginate = 15
contentDir = "src/content"
staticDir = "src/static"
themesDir = "src/themes"
publishDir = "build/public"
dataDir = "build/data"
pygmentsCodeFences = true
pygmentsStyle = "manni"

[taxonomies]
    tag = "tags"

[params]
    name = "hello.vectronic@gmail.com"
    description = "Personal blog"

[menu]
    [[menu.global]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags/"
    weight     = 0

    [[menu.global]]
    identifier = "archives"
    name       = "Archives"
    url        = "/archives/"
    weight     = 1
